export default [
  {
    title: "КОТ АНОНИМУС — ОТКУДА МЕМ? КТО ХОЗЯИН?",
    channelTitle: "небуди",
    publishTime: "2021-03-12T11:29:50Z",
    videoId: "xzo0Z6L6yyI",
    viewCount: "124499",
  },
  {
    title: "ПРЯТКИ НА КАРТЕ ВЕСЁЛЫЙ КОТ В БРАВЛ СТАРС! НОВЫЙ МИНИ РЕЖИМ BRAWL STARS",
    channelTitle: "Весёлый Кот",
    publishTime: "2021-03-12T11:20:24Z",
    videoId: "r-bzKy0kdik",
    viewCount: "89478",
  },
  {
    title: "LOVE STORY (Full Colour Special)",
    channelTitle: "Simon's Cat",
    publishTime: "2021-03-12T12:48:40Z",
    videoId: "zNpoIaHJhNc",
    viewCount: "66318",
  },
  {
    title: "Cat William and his cute golden kittens",
    channelTitle: "Teddy Kittens",
    publishTime: "2021-03-11T18:20:58Z",
    videoId: "OxhMYA76GUI",
    viewCount: "47547",
  },
  {
    title: "Весёлый Кот и Friday Night Funkin Прохождение",
    channelTitle: "Весёлый Кот",
    publishTime: "2021-03-12T08:34:56Z",
    videoId: "zXrc0e1WXF8",
    viewCount: "40657",
  },
  {
    title: "Кот против человека , Серия -371",
    channelTitle: "День Бомжа TV",
    publishTime: "2021-03-12T04:46:34Z",
    videoId: "63IQaAaRb2Y",
    viewCount: "27489",
  },
  {
    title: "Про еду. Сова греет еду попой. Кот жуёт еду совы. Дракон складывает бабочек в живот",
    channelTitle: "Yoll",
    publishTime: "2021-03-12T15:00:36Z",
    videoId: "bUVlCgxTLTk",
    viewCount: "22136",
  },
  {
    title: "ЛЕДИ БАГ И СУПЕР-КОТ | 🐞 НИНО 🔝 | СЕЗОН 2 | Официальный канал",
    channelTitle: "ЛЕДИ БАГ И СУПЕР-КОТ - официальный канал",
    publishTime: "2021-03-12T06:00:11Z",
    videoId: "pivfoOIm6mc",
    viewCount: "21189",
  },
  {
    title:
      "Cute cat carefully washes the chanterelle ) home zoo. милый кот моет лису .  cute animals",
    channelTitle: "zoo home",
    publishTime: "2021-03-12T06:52:22Z",
    videoId: "2TTSfF_MK4o",
    viewCount: "2986",
  },
  {
    title: "#1 «Случайность» Переписка Леди Баг и Супер Кот",
    channelTitle: "Łîą_Çāţ [•ПЕРЕПИСКИ•]",
    publishTime: "2021-03-12T06:02:03Z",
    videoId: "IBDgayl_lNs",
    viewCount: "593",
  },
];
